### ISSUE TITLE
Wizard currently only loads with `KC_HTTP_RELATIVE_PATH=/auth`

### ISSUE THREAD

**Issue by xgp** [p2-inc/idp-wizard#181]
Per https://github.com/p2-inc/keycloak-orgs/issues/242#issuecomment-2156010049 it appears the wizard only loads if `KC_HTTP_RELATIVE_PATH` is set to `/auth`.

Need to make sure it works for any/none relative path

**Comment by VipinGoyal** [comment]
If I add /auth as relative path, Im not able to see main UI in production mode, with /auth its working fine locally, there are some issues with hostname:v2 and /auth as relative path, and if I remove /auth wizard is not working.

**Comment by xgp** [comment]
@VipinGoyal you'd need to give me enough information to reproduce. What you wrote is insufficient.

> and if I remove /auth wizard is not working

Yes. That is what this bug is about.

**Comment by VipinGoyal** [comment]
Sure, Im running keycloak orgs  behind reverse proxy over coolify, and in order to have working idp wizard when I pass '/auth' as env key i.e. for **KC_HTTP_RELATIVE_PATH**, I found whole keycloak itself is not working. But If I remove given env key then its working fine, let me share my docker compose file which is working without given env value. 


```
version: '3'
volumes:
  postgres_data: null
  keycloak_data: null
services:
  postgres:
    image: 'postgres:16'
    environment:
      POSTGRES_DB: '${KC_DB:-keycloak}'
      POSTGRES_USER: '${KC_DB_USER:-coolify}'
      POSTGRES_PASSWORD: '${KC_DB_PASSWORD:-password}'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 30s
      timeout: 20s
      retries: 5
  keycloak:
    image: 'quay.io/phasetwo/phasetwo-keycloak:latest'
    environment:
      PROXY_ADDRESS_FORWARDING: 'true'
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL_DATABASE: '${KC_DB:-keycloak}'
      KC_DB_USERNAME: '${KC_DB_USER:-coolify}'
      KC_DB_PASSWORD: '${KC_DB_PASSWORD:-password}'
      KC_DB_URL: '${KC_DB_URL:-jdbc:postgresql://postgres:5432/keycloak}'
      KC_HOSTNAME: '${KC_HOSTNAME:-https://auth.example.com}'
      KC_HTTP_ENABLED: 'true'
      KC_PROXY_HEADERS: xforwarded
      KC_LOG_LEVEL: 'INFO,io.phasetwo:DEBUG'
      KC_TRANSACTION_XA_ENABLED: 'false'
      KC_TRANSACTION_JTA_ENABLED: 'false'
      KC_FEATURES: persistent-user-sessions
      KC_METRICS_ENABLED: 'true'
      KC_HEALTH_ENABLED: 'true'
      KC_HOSTNAME_DEBUG: 'true'
      KC_HTTP_MANAGEMENT_PORT: 9000
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        - CMD-SHELL
        - "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;"
      interval: 30s
      timeout: 20s
      retries: 5
    entrypoint: '/opt/keycloak/bin/kc.sh --verbose start --spi-email-template-provider=freemarker-plus-mustache --spi-email-template-freemarker-plus-mustache-enabled=true --spi-theme-cache-themes=false'

```


And if I tried to add following env key values inside **environment** sectioni.e.
KC_HTTP_RELATIVE_PATH or
KC_HOSTNAME_ADMIN // in order to have admin url over diffrent URL 

keycloak UI is not working.
